---
# Add 'cicd' label to any file changes inside .github dir
🚢📀cicd:
  - changed-files:
      - any-glob-to-any-file: [".github/*", ".github/**/*"]

# Add 'documentation' label to any file changes for the documentation files
📕documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

# Add 'configuration' label to any file changes for configuration files
🛠️configuration:
  - changed-files:
      - any-glob-to-any-file: ".config/**"
