---
name: Build Workflow

permissions:
  contents: read

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@v5

      - name: 🔄 Init PNPM
        uses: ./.github/actions/pnpm-init

      - name: 🔨 Build all
        run: pnpm build

      - name: ⏫ Upload app
        uses: actions/upload-artifact@v5
        with:
          name: astro-app
          path: apps/astro/dist
