---
name: Validate

permissions:
  contents: read

on:
  workflow_call:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@v6.0.2

      - name: 🔄 Init PNPM
        uses: ./.github/actions/pnpm-init

      - name: 🔬 Validate repo
        run: pnpm lint
