---
name: Test

permissions:
  contents: read

on:
  workflow_call:

jobs:
  validate:
    name: Test
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@v5

      - name: 🔄 Init PNPM
        uses: ./.github/actions/pnpm-init

      - name: 👨‍🔬👩‍🔬 Test repo
        run: pnpm test
