name: Default Pipeline

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  init:
    uses: ./.github/workflows/00-init.yml

  build:
    uses: ./.github/workflows/01-build.yml
    needs: [init]
    secrets: inherit

  lint:
    uses: ./.github/workflows/01-lint.yml
    needs: [init]
    secrets: inherit

  test:
    uses: ./.github/workflows/01-test.yml
    needs: [init]
    secrets: inherit

  deploy:
    uses: ./.github/workflows/02-deploy-gh-pages.yml
    if: ${{ github.event.pull_request == null  }}
    needs: [build, lint, test]
