name: Default Pipeline

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  init:
    uses: ./.github/workflows/00-init.yml

  build:
    uses: ./.github/workflows/01-build.yml
    needs: [init]
    secrets: inherit

  lint:
    uses: ./.github/workflows/01-lint.yml
    needs: [init]
    secrets: inherit

  test:
    uses: ./.github/workflows/01-test.yml
    needs: [init]
    secrets: inherit

  deploy:
    uses: ./.github/workflows/02-deploy-gh-pages.yml
    if: ${{ github.event.pull_request == null  }}
    needs: [build, lint, test]

  release:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [build, lint, test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v6

      - name: 🔄 Init PNPM
        uses: ./.github/actions/pnpm-init

      - run: |
          pnpm build --filter @db-ux/create-astro

      - id: changesets
        uses: changesets/action@v1.8.0
        with:
          publish: pnpm changeset publish
          title: 'chore: version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
          HUSKY: 0
