name: On Pull Request

on: pull_request

permissions:
  pull-requests: write
  contents: write
  actions: read
  security-events: write

jobs:
  dependabot:
    uses: ./.github/workflows/99-auto-merge.yml
